name: health_is_all
description: "HEALTH IS ALL - Health & Gamification Web App (Flutter Web / PWA)"
publish_to: 'none'
version: 2.1.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'
  flutter: ">=3.19.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.2
  flutter_riverpod: ^2.5.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  cupertino_icons: ^1.0.6
  http: ^1.2.2
  web: ^0.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/game/constellation_board_base.png
